### ISSUE TITLE
Menu shortcut does not work on macOS since wry 0.22

### ISSUE THREAD

**Issue by rhysd** [tauri-apps/wry#749]
**Describe the bug**

Key shotcut of menu item does not work on macOS since 0.22.0.

**Steps To Reproduce**

1. Save the following code and run
2. Application window launches
3. Enter `Cmd+Q`
4. Nothing happens and nothing is output to terminal console

```rust
fn main() -> wry::Result<()> {
  use wry::{
    application::{
      accelerator::Accelerator,
      event::{Event, StartCause, WindowEvent},
      event_loop::{ControlFlow, EventLoop},
      keyboard::{KeyCode, ModifiersState},
      menu::{MenuBar, MenuItemAttributes},
      window::WindowBuilder,
    },
    webview::WebViewBuilder,
  };

  let mut menu = MenuBar::new();
  let mut file_menu = MenuBar::new();
  file_menu.add_item(
    MenuItemAttributes::new("Quit").with_accelerators(&Accelerator::new(
      Some(ModifiersState::SUPER),
      KeyCode::KeyQ,
    )),
  );
  menu.add_submenu("File", true, file_menu);

  let event_loop = EventLoop::new();
  let window = WindowBuilder::new()
    .with_title("Hello World")
    .with_menu(menu)
    .build(&event_loop)?;
  let _webview = WebViewBuilder::new(window)?
    .with_url("https://example.com")?
    .build()?;

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;

    match event {
      Event::NewEvents(StartCause::Init) => println!("Wry has started!"),
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        ..
      } => *control_flow = ControlFlow::Exit,
      Event::MenuEvent { menu_id, .. } => {
        println!("Menu clicked! {:?}", menu_id);
        *control_flow = ControlFlow::Exit;
      }
      _ => (),
    }
  });
}
```

**Expected behavior**
'Menu clicked!' is output to terminal console and application quits successfully

**Screenshots**
N/A

**Platform and Versions (please complete the following information):**
OS: macOS 11
Rustc: rustc v1.65.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**

This seems a regression of v0.22.0. I confirmed it worked with v0.21.1.

Selecting 'Quit' from menu item works as intended.

**Comment by rhysd** [comment]
I bisected this repository.

- 008eca871155f393e5de1053bb1a9f63e1eafe82 reproduces this issue
- 61b7fec97fef2c28f5753b84d5e82c2d4b6bfc85 does not reproduce this issue

#745 seems related to this issue.

CC: @wusyong

**Comment by wusyong** [comment]
Looks like this is a regression after we don't replace TaoView.
I further test `tao`'s menu accelerator is fine.
If we remove `TaoView`'s `keyUp` and `keyDown` methods, example in wry can work again somehow.
We'll need some helps looking into why adding subview will cause keyinput being blocked in menu accelerator.

**Comment by wusyong** [comment]
Okay I found the cause is `doCommandBySelector` in TaoView.
Although it does nothing in tao, winit uses it for some text blocking.
But again this method is deprecated. We can remove this in tao and open an issue in winit to think what's the better way to do this I think.

**Comment by lucasfernog** [comment]
@wusyong can we patch this asap

**Comment by lucasfernog** [comment]
Fixed in tao v0.15.3.

**Comment by rhysd** [comment]
I confirmed that this issue was fixed after `cargo update`. Thank you for the quick fix.

**Comment by tw93** [comment]
when i run `npm run tauri build -- --target universal-apple-darwin`, the bug still exists.
but when i run `npm run tauri build -- --target x86_64-apple-darwin` and m1 is ok
and `npm run dev` is ok
